version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.4.0

    #working_directory: /tmp
    steps:
      - checkout
      - run:
          name: Creating Dummy Artifacts
          command: |
            echo "my artifact file" > /tmp/artifact-1;
            mkdir /tmp/artifacts;
            echo "my artifact files Dir" > /tmp/artifacts/artifact-2;
            echo $test
            #df -h
      - store_artifacts:
          path: /tmp/artifact-1
          destination: artifact-file

      - store_artifacts:
          path: /tmp/artifacts
   
  build2:
    docker:
      # DLC does nothing here, its caching depends on commonality of the image layers.
      - image: circleci/node:9.8.0-stretch-browsers
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      # DLC will explicitly cache layers here and try to avoid rebuilding.
      - run: docker build .
      
  machine_job:
    machine:
      image: default
    resource_class: medium  
    steps:
      - checkout
      - run:
          name: "Testing"
          command: echo "Hello Hi      
workflows:
  version: 2
  release:
    jobs:
    - build
       # context: team1_context
    #- cache_test 
    - build2
    - machine_job
